[package]
name = "oneterm-local"
description = "Local shell via PTY for OneTerm (alacritty_terminal::tty)."
publish = false
edition.workspace = true

[lints]
workspace = true

[dependencies]
oneterm-core.workspace = true
alacritty_terminal.workspace = true
async-channel.workspace = true
polling.workspace = true
log.workspace = true