[package]
name = "oneterm-ssh"
description = "SSH + SFTP implementation for OneTerm (russh)."
publish = false
edition.workspace = true

[features]
terminal-diagnostics = []

[lints]
workspace = true

[dependencies]
oneterm-core.workspace = true
oneterm-terminal.workspace = true
alacritty_terminal.workspace = true
async-channel.workspace = true
russh.workspace = true
tokio.workspace = true
log.workspace = true
russh-sftp.workspace = true
anyhow.workspace = true
tokio-util.workspace = true

[dev-dependencies]
oneterm-terminal = { workspace = true, features = ["test-support"] }