"""Render IN-0046 hotpath JSON reports as Markdown tables.

    python hotpath-tables.py raw/time-flood.json [N]

Prints, for every functions section in the report (timing or allocation), the top N
sites (default 15) by total and by average per call. The `oneterm_app::run` wrapper row
is left out: it is the whole run and only serves as the percentage denominator.
"""
import json
import sys

UNITS = {"ns": 1, "µs": 1e3, "us": 1e3, "ms": 1e6, "s": 1e9,
         "B": 1, "KB": 1024, "MB": 1024**2, "GB": 1024**3, "TB": 1024**4}


def value(text):
    """'8.62 ms' -> ns, '1.2 MB' -> bytes, '42' -> 42; 'N/A' -> None."""
    text = str(text).strip()
    if text in ("N/A", ""):
        return None
    parts = text.split()
    if len(parts) == 1:
        return float(parts[0])
    return float(parts[0]) * UNITS[parts[1]]


def table(rows, key, n, head):
    rows = sorted((r for r in rows if value(r[key]) is not None), key=lambda r: -value(r[key]))[:n]
    out = [f"| # | Site | Calls | Avg | P95 | Total | % |", "| --- | --- | ---: | ---: | ---: | ---: | ---: |"]
    for i, r in enumerate(rows, 1):
        name = r["name"].replace("oneterm_", "")
        out.append(f"| {i} | `{name}` | {r['calls']} | {r['avg']} | {r.get('p95', '')} | {r['total']} | {r['percent_total']} |")
    print(f"{head}\n")
    print("\n".join(out))
    print()


RUNS = ("time-idle", "time-flood", "time-flood-2", "time-tui", "alloc-bytes-idle",
        "alloc-count-idle", "alloc-bytes-flood", "alloc-count-flood", "alloc-bytes-tui",
        "alloc-count-tui")


def main():
    if sys.argv[1] == "--all":  # regenerate tables.md: python hotpath-tables.py --all > tables.md
        print("# IN-0046 hotpath tables (generated)\n")
        print("Generated by `python hotpath-tables.py --all` from the JSON reports in `raw/`. "
              "Timing is inclusive of nested sites; allocation figures are exclusive "
              "(hotpath's default). `oneterm_app::run` (the whole run) is omitted. "
              "Discussion: [`hotpath-evaluation.md`](hotpath-evaluation.md).\n")
        for run in RUNS:
            print(f"## {run}\n")
            report_tables(f"raw/{run}.json", 15)
        return
    report_tables(sys.argv[1], int(sys.argv[2]) if len(sys.argv) > 2 else 15)


def report_tables(path, n):
    report = json.load(open(path, encoding="utf-8"))
    for section, body in report.items():
        if not section.startswith("functions_") or not isinstance(body, dict):
            continue
        # An allocation build also times its sites, but the counting allocator is on
        # every allocation, so its durations are not comparable: use the timing build.
        if section == "functions_timing" and "functions_alloc" in report:
            continue
        rows = [r for r in body["data"] if r["name"] != "oneterm_app::run"]
        mode = body.get("profiling_mode", section)
        name = path.replace("\\", "/").split("/")[-1]
        print(f"### {name} -- {mode}, run {body.get('time_elapsed', '?')}\n")
        table(rows, "total", n, f"Top {n} by total")
        table(rows, "avg", n, f"Top {n} by average per call")


if __name__ == "__main__":
    main()
