[package]
name = "oneterm-ui"
description = "GPUI views, layout, theme, state for OneTerm."
publish = false
edition.workspace = true
build = "build.rs"

[features]
terminal-diagnostics = [
    "oneterm-local/terminal-diagnostics",
    "oneterm-ssh/terminal-diagnostics",
]

[lints]
workspace = true

[dependencies]
oneterm-core.workspace = true
oneterm-highlight.workspace = true
log.workspace = true

alacritty_terminal.workspace = true
gpui.workspace = true
gpui_platform.workspace = true
gpui-component.workspace = true
gpui-component-assets.workspace = true

anyhow.workspace = true
itertools = "0.14"
oneterm-local.workspace = true
oneterm-ssh.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
sysinfo.workspace = true
async-channel.workspace = true
rust-embed = "8.7"

[dev-dependencies]
gpui = { workspace = true, features = ["test-support"] }
oneterm-core = { workspace = true, features = ["test-support"] }