//! Build script for `oneterm-completion`.
//!
//! Walks `assets/**/*.json` at compile time and generates a static index of
//! `include_str!`ed catalog files into `$OUT_DIR/catalog_index.rs`. Each entry
//! is `(name, source, category, json)` where `source` (`external`/`manual`) and
//! `category` (`cmd`/`coreutils`/`powershell`/`windows`/`linux`/`common`) are
//! derived from the file's folder path (see docs/auto-completion/07 §5).
//!
//! This is the same "build-script-embeds-assets" pattern the `theme` crate uses
//! for icons: every command ships embedded in the binary with no runtime file
//! dependency (docs/auto-completion/02 §5.2).

use std::{
    env, fs,
    path::{Path, PathBuf},
};

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let assets = Path::new(&manifest_dir).join("assets");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let dest = Path::new(&out_dir).join("catalog_index.rs");

    println!("cargo:rerun-if-changed=assets");

    let mut files: Vec<PathBuf> = Vec::new();
    if assets.is_dir() {
        collect_json(&assets, &mut files);
    }
    // Deterministic ordering so regeneration is byte-stable.
    files.sort();

    let mut entries = String::new();
    for file in &files {
        // The catalog schema file is not a command node — skip it.
        if file.file_name().and_then(|n| n.to_str()) == Some("catalog.schema.json") {
            continue;
        }
        let Some((source, category)) = classify(&assets, file) else {
            continue;
        };
        let name = file
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or_default()
            .to_string();
        let abs = file.display().to_string().replace('\\', "\\\\");
        entries.push_str(&format!(
            "    ({name:?}, {source:?}, {category:?}, include_str!(\"{abs}\")),\n"
        ));
        println!("cargo:rerun-if-changed={}", file.display());
    }

    let generated = format!(
        "// @generated by build.rs — do not edit.\n\
         /// `(name, source, category, json)` for every embedded catalog file.\n\
         pub static CATALOG_FILES: &[(&str, &str, &str, &str)] = &[\n{entries}];\n"
    );
    fs::write(&dest, generated).expect("failed to write catalog_index.rs");
}

/// Recursively collect every `*.json` file under `dir`.
fn collect_json(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(read) = fs::read_dir(dir) else {
        return;
    };
    for entry in read.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_json(&path, out);
        } else if path.extension().and_then(|e| e.to_str()) == Some("json") {
            out.push(path);
        }
    }
}

/// Derive `(source, category)` from a file path relative to `assets/`.
///
/// - `external/<category>/<cmd>.json` → source `external`, category = the folder.
/// - `manual/windows/cmd/<cmd>.json`  → source `manual`, category `windows`.
/// - `manual/windows/powershell/...`  → source `manual`, category `powershell`.
/// - `manual/linux/<cmd>.json`        → source `manual`, category `linux`.
/// - `manual/common/<cmd>.json`       → source `manual`, category `common`.
fn classify(assets: &Path, file: &Path) -> Option<(String, String)> {
    let rel = file.strip_prefix(assets).ok()?;
    let parts: Vec<String> = rel
        .parent()?
        .components()
        .map(|c| c.as_os_str().to_string_lossy().to_string())
        .collect();
    match parts.as_slice() {
        [source, category] if source == "external" => {
            Some(("external".to_string(), category.clone()))
        }
        [source, os, sub] if source == "manual" && os == "windows" => {
            // windows/cmd → windows ; windows/powershell → powershell
            let category = if sub == "powershell" {
                "powershell"
            } else {
                "windows"
            };
            Some(("manual".to_string(), category.to_string()))
        }
        [source, category] if source == "manual" => {
            // linux, common
            Some(("manual".to_string(), category.clone()))
        }
        _ => None,
    }
}
