#!/usr/bin/env python3
"""Generate / verify THIRD-PARTY-NOTICES.md from the resolved Cargo dependency graph.

Usage:
    python scripts/third-party-notices.py            # rewrite THIRD-PARTY-NOTICES.md
    python scripts/third-party-notices.py --check    # exit 1 when the file is stale

Works offline: it only runs `cargo metadata` (which resolves against Cargo.lock) and
reads the crate manifests already in the local Cargo cache. Every crate reachable from
the shipped binary (`oneterm-app`, normal + build dependencies, all release targets) is
listed with its version, declared SPDX licence expression and source. The hand-written
header (bundled non-Rust components, vendored test data, GPL analysis) lives in
``HEADER`` below — edit it here, not in the generated file.

Section 1 (the bundled ConPTY pair) is generated from
``crates/app/assets/conpty-manifest.json``, written by ``scripts/bump-conpty.ps1``.
Generating it also verifies the tracked binaries still hash to what the manifest
records, so ``--check`` fails when the assets and the manifest drift apart.
"""

from __future__ import annotations

import hashlib
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "THIRD-PARTY-NOTICES.md"
ASSETS = ROOT / "crates" / "app" / "assets"
CONPTY_MANIFEST = ASSETS / "conpty-manifest.json"
APP_PACKAGE = "oneterm-app"
# Same target set as deny.toml [graph].targets — the platforms OneTerm ships for.
TARGETS = (
    "x86_64-pc-windows-msvc",
    "aarch64-pc-windows-msvc",
    "x86_64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
)
# Crates whose manifest has no `license` field; the effective licence was established by
# inspection (docs/license-analysis.md §2.1) and is clarified the same way in deny.toml.
LICENSE_CLARIFICATIONS = {
    "gpui_util": "Apache-2.0 (no manifest field; LICENSE-APACHE in the Zed monorepo)",
    "gpui_shared_string": "Apache-2.0 (no manifest field; LICENSE-APACHE in the Zed monorepo)",
}

HEADER = """\
# Third-party notices

OneTerm is licensed under the Apache License 2.0 (see [`LICENSE`](LICENSE) and
[`NOTICE`](NOTICE)). The distributed binaries also contain or redistribute the
third-party components below. This file is **generated** by
`python scripts/third-party-notices.py` (CI verifies it with `--check`); edit the
script's header text or the manifests, not this file.

{{CONPTY}}
MIT licence text (Windows Terminal):

> Copyright (c) Microsoft Corporation.
>
> Permission is hereby granted, free of charge, to any person obtaining a copy of this
> software and associated documentation files (the "Software"), to deal in the Software
> without restriction, including without limitation the rights to use, copy, modify,
> merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
> permit persons to whom the Software is furnished to do so, subject to the following
> conditions: The above copyright notice and this permission notice shall be included
> in all copies or substantial portions of the Software. THE SOFTWARE IS PROVIDED
> "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
> TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
> NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
> CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
> OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
> DEALINGS IN THE SOFTWARE.

## 2. Vendored test data (not linked into any binary)

| Data | Upstream | Base revision | Licence | Attribution |
|---|---|---|---|---|
| VT parity corpus, 45 reference captures (`crates/tools/corpus/alacritty-ref/`) | <https://github.com/alacritty/alacritty> via <https://github.com/zed-industries/alacritty> | `fcf32feacb367b75ec84dd40f041e4fd411d3cc1` | Apache-2.0 | `crates/tools/corpus/NOTICE` |

Copyright 2016 Joe Wilm, The Alacritty Project Contributors. Only `alacritty.recording`
(carried as `recording`), `size.json` and `config.json` are reused, unmodified — 936 KiB.
Upstream's `grid.json` (44 MiB) is deliberately not carried. The `grid.expect`,
`state.expect` and `expected-diffs.json` files next to each recording are OneTerm's own
work (Apache-2.0), generated by the engine being replaced and frozen at `US-0072`
(`docs/spec-intakes/IN-0029-vt-engine/low-level-design/testing-and-bench.md`). That
engine — a patched fork of `alacritty_terminal` and `vte`, vendored until `US-0087` —
is no longer part of OneTerm: `oneterm-vt` (`crates/vt`) is first-party Apache-2.0 code
and the recordings above are the only Alacritty-derived material left.

### 2.1 Derived algorithms (no source copied)

| Where | Derived from | Licence | What was taken |
|---|---|---|---|
| `crates/vt/src/reflow/columns.rs` | `avt`'s `Reflow` iterator, <https://github.com/asciinema/avt> | Apache-2.0 | The **approach only**: group rows into logical lines on the wrap flag, trim, redistribute at the new width. No `avt` source is copied; the storage, the cell representation and the anchor mechanism are OneTerm's. |
| `crates/pty/src/windows*.rs` | Alacritty's `alacritty_terminal/src/tty/windows/`, <https://github.com/alacritty/alacritty> | Apache-2.0 | Several fragments and the structure of the Windows backend — the MSVCRT argument escaping (itself adapted from the Rust standard library), the environment-block builder, the child-exit wait callback and the pollable-pipe registration semantics. All modified; each file carries the notice in its header. |

Apache-2.0 § 4(b) notices live in the source headers of the files listed above, which state
what was changed.

## 3. Copyleft analysis

Three Zed crates (`zlog`, `ztracing`, `ztracing_macro`) declare `GPL-3.0-or-later`.
`ztracing`/`ztracing_macro` are dual-licensed (Apache-2.0 chosen); `zlog` is GPL-only
but is compiled only behind `cfg(ztracing)` / `cfg(test)` and is not linked into the
release binary. Details and verification method: `docs/license-analysis.md`;
enforcement: `deny.toml` (`cargo deny check licenses`, CI job `cargo-deny`).

`crates/tools/src/bin/doom-fire.rs` (developer diagnostic, **not** part of any release)
is a Rust port of DOOM-fire-zig and keeps that project's GPL-3.0 licence; the
`oneterm-tools` package therefore declares `Apache-2.0 AND GPL-3.0-only`.

## 4. Rust crates linked into the release binary

Every crate reachable from `oneterm-app` (normal + build dependencies) for the release
targets in `deny.toml`. Licence = the SPDX expression declared by the crate; source =
crates.io unless a git URL is shown. Full licence texts ship inside each crate's
package in the Cargo registry / git checkout.

"""


def conpty_section() -> str:
    """Render section 1 from the ConPTY manifest, verifying the tracked binaries.

    Raises SystemExit when an asset no longer matches the SHA-256 the manifest
    records — a bump that forgot `scripts/bump-conpty.ps1`, or an edited binary.
    """
    manifest = json.loads(CONPTY_MANIFEST.read_text(encoding="utf-8"))
    rows = []
    digests = []
    for name, entry in manifest["files"].items():
        actual = hashlib.sha256((ASSETS / name).read_bytes()).hexdigest()
        if actual != entry["sha256"]:
            raise SystemExit(
                f"error: crates/app/assets/{name} does not match conpty-manifest.json\n"
                f"  manifest {entry['sha256']}\n  on disk  {actual}\n"
                "  bump both with `pwsh scripts/bump-conpty.ps1 -Version <version>`"
            )
        rows.append(
            f"| `{name}` | {entry['file_version']} (Windows Terminal) "
            f"| <{manifest['project']}> "
            f"| {manifest['licence']} — Copyright (c) Microsoft Corporation |"
        )
        digests.append(f"- `{name}` `{actual}`")
    return "\n".join(
        [
            "## 1. Bundled non-Rust components (Windows releases)",
            "",
            "| Component | Version | Source | Licence |",
            "|---|---|---|---|",
            *rows,
            "",
            "`crates/app/build.rs` copies both files from `crates/app/assets/` next to",
            "`oneterm.exe`, so ConPTY uses Windows Terminal's console host instead of the inbox",
            "`conhost.exe` (Sixel passthrough, host control); without them OneTerm falls back to",
            "the OS ConPTY. They are unmodified x64 binaries from the NuGet package",
            f"`{manifest['package']}` {manifest['version']} (downloaded {manifest['downloaded']}):",
            "",
            f"<{manifest['source']}>",
            "",
            "Bump them with `pwsh scripts/bump-conpty.ps1`, which also writes",
            "`crates/app/assets/conpty-manifest.json` — the source of this section. SHA-256 of",
            "the tracked copies:",
            "",
            *digests,
            "",
        ]
    )


def cargo_metadata() -> dict:
    cmd = ["cargo", "metadata", "--format-version", "1", "--locked"]
    for target in TARGETS:
        cmd += ["--filter-platform", target]
    return json.loads(subprocess.check_output(cmd, cwd=ROOT).decode("utf-8"))


def reachable_from(meta: dict, root_name: str) -> set[str]:
    nodes = {node["id"]: node for node in meta["resolve"]["nodes"]}
    root_id = next(p["id"] for p in meta["packages"] if p["name"] == root_name)
    seen: set[str] = set()
    stack = [root_id]
    while stack:
        pkg_id = stack.pop()
        if pkg_id in seen:
            continue
        seen.add(pkg_id)
        for dep in nodes[pkg_id]["deps"]:
            kinds = {k.get("kind") for k in dep["dep_kinds"]} or {None}
            # Skip dev-dependency-only edges: they are not linked into the binary.
            if kinds <= {"dev"}:
                continue
            stack.append(dep["pkg"])
    return seen


def source_label(pkg: dict) -> str:
    source = pkg.get("source") or ""
    if source.startswith("registry+"):
        return "crates.io"
    if source.startswith("git+"):
        url = source[len("git+"):].split("?", 1)[0].split("#", 1)[0]
        return url
    if not source:
        return "local path dependency"
    return source


def render(meta: dict) -> str:
    # OneTerm's own workspace crates are first-party (and their version changes on
    # every release), so they are left out of the third-party table.
    wanted = reachable_from(meta, APP_PACKAGE) - set(meta["workspace_members"])
    packages = sorted(
        (p for p in meta["packages"] if p["id"] in wanted),
        key=lambda p: (p["name"].lower(), p["version"]),
    )
    header = HEADER.replace("{{CONPTY}}", conpty_section())
    lines = [header, "| Crate | Version | Licence | Source |", "|---|---|---|---|"]
    for pkg in packages:
        licence = (
            pkg.get("license")
            or LICENSE_CLARIFICATIONS.get(pkg["name"])
            or ("(see LICENSE file in package)" if pkg.get("license_file") else "UNKNOWN")
        )
        lines.append(f"| `{pkg['name']}` | {pkg['version']} | {licence} | {source_label(pkg)} |")
    lines.append("")
    lines.append(f"_{len(packages)} third-party packages._")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    check = "--check" in sys.argv[1:]
    text = render(cargo_metadata())
    if check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current.replace("\r\n", "\n") != text:
            print(
                "error: THIRD-PARTY-NOTICES.md is stale; run `python scripts/third-party-notices.py`",
                file=sys.stderr,
            )
            raise SystemExit(1)
        print("THIRD-PARTY-NOTICES.md is up to date.")
        return
    OUTPUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT.relative_to(ROOT).as_posix()}")


if __name__ == "__main__":
    main()
